name = "Mogged"
license = "MIT"
licenselink = "https://github.com/kylediaz/mogged/blob/master/LICENSE"
description = "Simple theme for combined portfolios and blogs"
homepage = "https://github.com/kylediaz/mogged/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Kyle Diaz"
  homepage = "https://kylediaz.com"

[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "bw"
    tabWidth = 4

